// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoupAndSoup.Data;

#nullable disable

namespace SoupAndSoup.Data.Migrations
{
    [DbContext(typeof(SoapAndSoulContext))]
    [Migration("20250606185032_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoupAndSoup.Data.Models.AmountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("AmountTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Грам",
                            ShortName = "г"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Мілілітр",
                            ShortName = "мл"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Штука",
                            ShortName = "шт"
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngredientTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.IngredientImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.ToTable("IngredientImages");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.IngredientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AmountTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AmountTypeId");

                    b.ToTable("IngredientTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountTypeId = 3,
                            Name = "Форма для мила",
                            Order = 1,
                            ShortName = "форму"
                        },
                        new
                        {
                            Id = 2,
                            AmountTypeId = 1,
                            Name = "Мильна основа",
                            Order = 2,
                            ShortName = "основу"
                        },
                        new
                        {
                            Id = 3,
                            AmountTypeId = 2,
                            Name = "Запашка",
                            Order = 3,
                            ShortName = "запашку"
                        },
                        new
                        {
                            Id = 4,
                            AmountTypeId = 2,
                            Name = "Пігмент",
                            Order = 4,
                            ShortName = "пігмент"
                        },
                        new
                        {
                            Id = 5,
                            AmountTypeId = 2,
                            Name = "Ефірне масло",
                            Order = 5,
                            ShortName = "ефірне масло"
                        },
                        new
                        {
                            Id = 6,
                            AmountTypeId = 2,
                            Name = "Екстракт",
                            Order = 6,
                            ShortName = "екстракт"
                        },
                        new
                        {
                            Id = 7,
                            AmountTypeId = 2,
                            Name = "Інструменти",
                            Order = 7,
                            ShortName = "інструмент"
                        },
                        new
                        {
                            Id = 8,
                            AmountTypeId = 3,
                            Name = "Інші",
                            Order = 8,
                            ShortName = ""
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeImages");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Ingredient", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.IngredientType", "IngredientType")
                        .WithMany("Ingredients")
                        .HasForeignKey("IngredientTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.IngredientImage", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Ingredient", "Ingredient")
                        .WithMany("Images")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.IngredientType", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.AmountType", "AmountType")
                        .WithMany("IngredientType")
                        .HasForeignKey("AmountTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AmountType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeImage", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeIngredient", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.AmountType", b =>
                {
                    b.Navigation("IngredientType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Ingredient", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.IngredientType", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Recipe", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RecipeIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
