// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoupAndSoup.Data;

#nullable disable

namespace SoupAndSoup.Data.Migrations
{
    [DbContext(typeof(SoapAndSoulContext))]
    partial class SoapAndSoulContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComponentTypeBuyMeasureTypes", b =>
                {
                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureTypesId")
                        .HasColumnType("int");

                    b.HasKey("ComponentTypesId", "MeasureTypesId");

                    b.HasIndex("MeasureTypesId");

                    b.ToTable("ComponentTypeBuyMeasureTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ComponentTypesId = 1,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 2,
                            MeasureTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 3,
                            MeasureTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 4,
                            MeasureTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 4,
                            MeasureTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 5,
                            MeasureTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 6,
                            MeasureTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 7,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 8,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 9,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 10,
                            MeasureTypesId = 1
                        });
                });

            modelBuilder.Entity("ComponentTypeCosmeticTypes", b =>
                {
                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<int>("CosmeticTypesId")
                        .HasColumnType("int");

                    b.HasKey("ComponentTypesId", "CosmeticTypesId");

                    b.HasIndex("CosmeticTypesId");

                    b.ToTable("ComponentTypeCosmeticTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ComponentTypesId = 1,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 2,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 3,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 3,
                            CosmeticTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 4,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 5,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 6,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 7,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 8,
                            CosmeticTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 9,
                            CosmeticTypesId = 2
                        },
                        new
                        {
                            ComponentTypesId = 10,
                            CosmeticTypesId = 2
                        });
                });

            modelBuilder.Entity("ComponentTypeUseMeasureTypes", b =>
                {
                    b.Property<int>("ComponentTypesId")
                        .HasColumnType("int");

                    b.Property<int>("MeasureTypesId")
                        .HasColumnType("int");

                    b.HasKey("ComponentTypesId", "MeasureTypesId");

                    b.HasIndex("MeasureTypesId");

                    b.ToTable("ComponentTypeUseMeasureTypes", (string)null);

                    b.HasData(
                        new
                        {
                            ComponentTypesId = 1,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 2,
                            MeasureTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 3,
                            MeasureTypesId = 3
                        },
                        new
                        {
                            ComponentTypesId = 4,
                            MeasureTypesId = 3
                        },
                        new
                        {
                            ComponentTypesId = 4,
                            MeasureTypesId = 1
                        },
                        new
                        {
                            ComponentTypesId = 5,
                            MeasureTypesId = 3
                        },
                        new
                        {
                            ComponentTypesId = 6,
                            MeasureTypesId = 3
                        },
                        new
                        {
                            ComponentTypesId = 7,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 8,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 9,
                            MeasureTypesId = 4
                        },
                        new
                        {
                            ComponentTypesId = 10,
                            MeasureTypesId = 1
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyAmount")
                        .HasColumnType("int");

                    b.Property<int>("BuyMeasureTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CosmeticTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SuggestedAmount")
                        .HasColumnType("int");

                    b.Property<int>("UseMeasureTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyMeasureTypeId");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("CosmeticTypeId");

                    b.HasIndex("Name");

                    b.HasIndex("UseMeasureTypeId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.ComponentImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.ToTable("ComponentImages");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyAmount")
                        .HasColumnType("int");

                    b.Property<bool>("IsSingleSelected")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyAmount = 1,
                            IsSingleSelected = true,
                            Name = "Форма для мила",
                            Order = 1,
                            ShortName = "форму"
                        },
                        new
                        {
                            Id = 2,
                            BuyAmount = 200,
                            IsSingleSelected = false,
                            Name = "Мильна основа",
                            Order = 2,
                            ShortName = "основу"
                        },
                        new
                        {
                            Id = 3,
                            BuyAmount = 10,
                            IsSingleSelected = false,
                            Name = "Запашка",
                            Order = 3,
                            ShortName = "запашку"
                        },
                        new
                        {
                            Id = 4,
                            BuyAmount = 10,
                            IsSingleSelected = false,
                            Name = "Пігмент",
                            Order = 4,
                            ShortName = "пігмент"
                        },
                        new
                        {
                            Id = 5,
                            BuyAmount = 10,
                            IsSingleSelected = false,
                            Name = "Ефірне масло",
                            Order = 5,
                            ShortName = "ефірне масло"
                        },
                        new
                        {
                            Id = 6,
                            BuyAmount = 10,
                            IsSingleSelected = false,
                            Name = "Екстракт",
                            Order = 6,
                            ShortName = "екстракт"
                        },
                        new
                        {
                            Id = 7,
                            BuyAmount = 1,
                            IsSingleSelected = false,
                            Name = "Інструменти",
                            Order = 7,
                            ShortName = "інструмент"
                        },
                        new
                        {
                            Id = 8,
                            BuyAmount = 1,
                            IsSingleSelected = false,
                            Name = "Інші",
                            Order = 8,
                            ShortName = ""
                        },
                        new
                        {
                            Id = 9,
                            BuyAmount = 1,
                            IsSingleSelected = true,
                            Name = "Флакон для парфумів",
                            Order = 1,
                            ShortName = "флакон"
                        },
                        new
                        {
                            Id = 10,
                            BuyAmount = 500,
                            IsSingleSelected = false,
                            Name = "Основа для парфумів",
                            Order = 2,
                            ShortName = "основу"
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.CosmeticType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CosmeticTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Мило"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Духи"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Всі"
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.MeasureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("MeasureTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Грам",
                            ShortName = "г"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Мілілітр",
                            ShortName = "мл"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Краплі",
                            ShortName = "крап"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Штука",
                            ShortName = "шт"
                        });
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CosmeticTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfCreate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("PreparationTime")
                        .HasColumnType("time");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CosmeticTypeId");

                    b.HasIndex("Name");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeComponent", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecipeId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("RecipeComponents");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeImages");
                });

            modelBuilder.Entity("ComponentTypeBuyMeasureTypes", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.ComponentType", null)
                        .WithMany()
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.MeasureType", null)
                        .WithMany()
                        .HasForeignKey("MeasureTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ComponentTypeCosmeticTypes", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.ComponentType", null)
                        .WithMany()
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.CosmeticType", null)
                        .WithMany()
                        .HasForeignKey("CosmeticTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComponentTypeUseMeasureTypes", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.ComponentType", null)
                        .WithMany()
                        .HasForeignKey("ComponentTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.MeasureType", null)
                        .WithMany()
                        .HasForeignKey("MeasureTypesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Component", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.MeasureType", "BuyMeasureType")
                        .WithMany("ComponentsUsingAsBuyMeasureType")
                        .HasForeignKey("BuyMeasureTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.CosmeticType", "CosmeticType")
                        .WithMany()
                        .HasForeignKey("CosmeticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.MeasureType", "UseMeasureType")
                        .WithMany("ComponentsUsingAsUseMeasureType")
                        .HasForeignKey("UseMeasureTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BuyMeasureType");

                    b.Navigation("ComponentType");

                    b.Navigation("CosmeticType");

                    b.Navigation("UseMeasureType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.ComponentImage", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Component", "Component")
                        .WithMany("Images")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Component");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Recipe", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.CosmeticType", "CosmeticType")
                        .WithMany()
                        .HasForeignKey("CosmeticTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosmeticType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeComponent", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Component", "Component")
                        .WithMany("RecipeComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoupAndSoup.Data.Models.Recipe", "Recipe")
                        .WithMany("RecipeComponents")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.RecipeImage", b =>
                {
                    b.HasOne("SoupAndSoup.Data.Models.Recipe", "Recipe")
                        .WithMany("Images")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Component", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RecipeComponents");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.MeasureType", b =>
                {
                    b.Navigation("ComponentsUsingAsBuyMeasureType");

                    b.Navigation("ComponentsUsingAsUseMeasureType");
                });

            modelBuilder.Entity("SoupAndSoup.Data.Models.Recipe", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("RecipeComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
